[package]
name = "koe-audio"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.81", features = ["backtrace"] }
tokio = { version = "1.37.0", features = ["rt", "process", "io-util"] }
log = "0.4.21"
