[package]
name = "koe-db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.82", features = ["backtrace"] }
redis = { version = "0.27.0", default-features = false, features = ["aio", "tokio-comp"] }
